server:
  port: ${MYPORT}
# management:
#  server:
#    port: 8088
#  endpoint:
#    health:
#      enabled: true

logging:
  level:
    org.springframework.*: DEBUG
    io.netty.*: DEBUG


limdongjin:
  ignasr:
    cors:
      origin: ${ALLOWORIGIN}
    kafka:
      bootstrapservers: ${BOOTSTRAPSERVERS}
      sasljaasconfig: ${SASLJAASCONFIG}
    ignite:
      namespace: ${NAMESPACE}     # limdongjin
      servicename: ${IGNITESERVICENAME} # ignite-service
      addresses: ${IGNITEADDRESSES}     # ignite-service:10800
