server:
  port: 8088

limdongjin:
  stomasr:
    cors:
      origin: localhost:8080
    kafka:
      bootstrapservers: localhost:9092
      sasljaasconfig: fakeconfig
spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer