server:
  port: ${MYPORT}

#management:
#  server:
#    port: 8089
#  endpoint:
#    health:
#      enabled: true

#logging:
#  level:
#    org.springframework.*: DEBUG
#    io.netty.*: DEBUG

limdongjin:
  stomasr:
    cors:
      origin: ${ALLOWORIGIN}
    kafka:
      bootstrapservers: ${BOOTSTRAPSERVERS}
      sasljaasconfig: ${SASLJAASCONFIG}

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
