server:
  port: ${MYPORT}

limdongjin:
  stomasr:
    cors:
      origin: ${ALLOWORIGIN}
    kafka:
      bootstrapservers: ${BOOTSTRAPSERVERS}
      sasljaasconfig: ${SASLJAASCONFIG}

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
