server:
  port: ${MYPORT}

logging:
  level:
    org.springframework.*: DEBUG
    io.netty.*: DEBUG

limdongjin:
  ignasr:
    cors:
      origin: ${ALLOWORIGIN}
    kafka:
      bootstrapservers: ${BOOTSTRAPSERVERS}
      sasljaasconfig: ${SASLJAASCONFIG}
    ignite:
      namespace: ${NAMESPACE}     # limdongjin
      servicename: ${IGNITESERVICENAME} # ignite-service
      addresses: ${IGNITEADDRESSES}     # ignite-service:10800
