apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka-cluster
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls # scram-sha-512
    authorization:
      type: simple
      superUsers:
        - ignasr
    config:
      inter.broker.protocol.version: "3.3"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 2
        memory: 5Gi
    storage:
      type: jbod
      volumes:      
        - id: 0
          type: persistent-claim
          size: 2Gi 
          deleteClaim: false
  zookeeper:
    replicas: 3
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 3
        memory: 6Gi
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: false
  entityOperator: 
    tlsSidecar:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 3Gi
    topicOperator:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 3Gi
    userOperator: 
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 3Gi

